### ISSUE TITLE
Can't save changes to entities (on CWRC Production)

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms#4]
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/0af03346-d5b3-42a1-90d6-84c29ddce8cd)

**Comment by ilovan** [comment]
OBJECT: https://cwrc.ca/sites/default/libraries/cwrc-entity-management-forms-static/build/place?entityId=reed:cae29296-ecd6-4e89-a10d-a4750fb2486b

**Comment by ajmacdonald** [comment]
Issue moved to [cwrc/cwrc-entity-management-forms-static #62](https://github.com/cwrc/cwrc-entity-management-forms-static/issues/62) via [**ZenHub**](https://www.zenhub.com/)
